# This script converts the .ui form generated by QtCreator
# into the .py equivalent using PySide2, as well as cleaning up an
# error causing set of lines involving 'placeholder test' and 'palettes' in the generated form

pyside2-uic form.ui -o ui_form.py
sed -i '/QPalette.PlaceholderText/d' ui_form.py 
echo "Incompatible bits removed..." 
echo "Say hello to your brand-new, shiny GOOEY"